-- MySQL Script generated by MySQL Workbench
-- Sat Jul  1 19:43:39 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema TweetsDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TweetsDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TweetsDB` DEFAULT CHARACTER SET utf8mb4 ;
USE `TweetsDB` ;

-- -----------------------------------------------------
-- Table `TweetsDB`.`Tweets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TweetsDB`.`Tweets` (
  `id` BIGINT(20) NOT NULL,
  `user` BIGINT(20) NOT NULL,
  `text` VARCHAR(170) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `hashtags_c` VARCHAR(200) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `numberOfHashtags_c` TINYINT(1) NULL DEFAULT NULL,
  `quoted_status` BIGINT(20) NULL DEFAULT NULL,
  `retweeted_status` BIGINT(20) NULL DEFAULT NULL,
  `favorite_count` INT(11) NULL DEFAULT NULL,
  `favorited` TINYINT(4) NULL DEFAULT NULL,
  `retweet_count` INT(11) NULL DEFAULT NULL,
  `retweeted` TINYINT(4) NULL DEFAULT NULL,
  `possibly_sensitive` TINYINT(4) NULL DEFAULT NULL,
  `withheld_copyright` TINYINT(4) NULL DEFAULT NULL,
  `annotationMethod` TINYINT(4) NULL DEFAULT NULL,
  `maliciousMark` TINYINT(4) NULL DEFAULT NULL,
  `country` VARCHAR(60) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `city` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `longtitude_latitude` VARCHAR(200) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `TweetsDB`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TweetsDB`.`User` (
  `id` BIGINT(20) NOT NULL,
  `followers_count` INT(11) NULL DEFAULT NULL,
  `friends_count` INT(11) NULL DEFAULT NULL,
  `description` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `url` VARCHAR(110) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `contributors_enabled` TINYINT(4) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `default_profile` TINYINT(4) NULL DEFAULT NULL,
  `default_profile_image` TINYINT(4) NULL DEFAULT NULL,
  `favourites_count` INT(11) NULL DEFAULT NULL,
  `is_translator` TINYINT(4) NULL DEFAULT NULL,
  `listed_count` INT(11) NULL DEFAULT NULL,
  `name` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `notifications` TINYINT(4) NULL DEFAULT NULL,
  `protected` TINYINT(4) NULL DEFAULT NULL,
  `screen_name` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `statuses_count` INT(11) NULL DEFAULT NULL,
  `verified` TINYINT(4) NULL DEFAULT NULL,
  `follow_request_sent` TINYINT(4) NULL DEFAULT NULL,
  `following` INT(11) NULL DEFAULT NULL,
  `location` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `followers` VARCHAR(1000) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `followees` VARCHAR(1000) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `updateTime` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
